// const UNPROCESSABLE = 422;
const CREATED = 201;
const OK = 200;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const CONFLICT = 409;
// const NO_CONTENT = 204;

module.exports = {
  // UNPROCESSABLE,
  CREATED,
  OK,
  BAD_REQUEST,
  UNAUTHORIZED,
  NOT_FOUND,
  CONFLICT,
  // NO_CONTENT,
};
