const UNPROCESSABE_ENTITY = 422;
const NOT_FOUND = 404;
const CREATED = 201;
const OK = 200;
const ID_LENGTH = 24;
const BAD_REQUEST = 400;
const CONFLICT = 409;
const UNAUTHORIZED = 401;
const MIN_PASS_LENGTH = 8;
const NO_CONTENT = 204;

module.exports = {
  UNPROCESSABE_ENTITY,
  NOT_FOUND,
  CREATED,
  OK,
  ID_LENGTH,
  BAD_REQUEST,
  CONFLICT,
  UNAUTHORIZED,
  MIN_PASS_LENGTH,
  NO_CONTENT,
};